FROM node:20.10.0 AS builder
WORKDIR /app
COPY /*.json ./
COPY . .
RUN npm i -g @nestjs/cli
RUN npm i
RUN npm run build

FROM node:20.10.0
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 5000
CMD ["npm", "run", "start:prod"]